### ISSUE TITLE
The predicted derivative.

### ISSUE THREAD

**Issue by Dionysus7777777** [dynamicslab/pykoopman#50]
Is there a function that can predict the derivative with respect to time of a certain state variable?

**Comment by fdu-goya** [comment]
Hello, I noticed that you have conducted in-depth research using pykoopman. I have also recently been studying the application of pyKoopman to different nonlinear dynamical systems. Could we exchange insights on its usage? I would be very happy to get in touch with you. Thank you.

**Comment by fdu-goya** [comment]
您好，很高兴收到您的回复。我主要聚焦于使用pykoopman包里的NNDMD模块，我在使用的过程中有如下问题:第一，原来的代码里面主要使用的是LBFGS优化器进行优化，使用ADAM优化器得到的效果较差。第二,我把NNDMD模型用于其他的非线性动力学系统的koopman算子的学习，例如duffing振荡子系统，von der pol振荡子系统，所得的结果不能准确的计算其koopman算子，不管是使用LBFGS优化器还是ADAM优化器。我想请问您在使用NNDMD应用到其他的非线性动力学系统上有什么经验，如果可行的话，能不能借鉴您使用NNDMD时应用的示例，供我进一步学习理解。很感谢您的回复，谢谢！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dynamicslab/pykoopman"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年5月11日(星期天) 下午4:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dynamicslab/pykoopman] The predicted derivative. (Issue #50)



 Dionysus7777777 left a comment (dynamicslab/pykoopman#50)
 你好，欢迎交流，鉴于我感觉你也是中国人，所以我直接用中文回复你了，你遇到了什么困难吗？欢迎可以把问题发到这个邮箱，如果我有相关经验我会解答的。 <br&gt; <br&gt; <br&gt; <br&gt; 发自我的iPhone <br&gt; <br&gt; <br&gt; ------------------ Original ------------------ <br&gt; From: goya-ddddd ***@***.***&amp;amp;gt; <br&gt; Date: Sun,May 11,2025 1:13 AM <br&gt; To: dynamicslab/pykoopman ***@***.***&amp;amp;gt; <br&gt; Cc: Dionysus7777777 ***@***.***&amp;amp;gt;, State change ***@***.***&amp;amp;gt; <br&gt; Subject: Re: [dynamicslab/pykoopman] The predicted derivative. (Issue #50) <br&gt; <br&gt; <br&gt; <br&gt;  fdu-goya left a comment (dynamicslab/pykoopman#50) <br&gt;   <br&gt; Hello, I noticed that you have conducted in-depth research using pykoopman. I have also recently been studying the application of pyKoopman to different nonlinear dynamical systems. Could we exchange insights on its usage? I would be very happy to get in touch with you. Thank you. <br&gt;   <br&gt; — <br&gt; Reply to this email directly, view it on GitHub, or unsubscribe. <br&gt; You are receiving this because you modified the open/close state.Message ID: ***@***.***&amp;amp;gt;

**Comment by Dionysus7777777** [comment]
您好，欢迎交流，但是今天我有一些忙，我们可以下周聊一下。优化器的问题我遇到过，这个似乎和具体问题有关，我建议使用lbfgs优化器，具体原理可能不太清楚。第二个问题，首先我想知道你是否有切换过激活函数，你可以看看我和作者的另外一个issue对话，里面有提到升维的网络应该用relu，或者其他非线性函数，降维的网络则需要使用linear。



发自我的iPhone


------------------ Original ------------------
From: goya-ddddd ***@***.***&gt;
Date: Sun,May 11,2025 5:09 PM
To: dynamicslab/pykoopman ***@***.***&gt;
Cc: Dionysus7777777 ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [dynamicslab/pykoopman] The predicted derivative. (Issue #50)



 fdu-goya left a comment (dynamicslab/pykoopman#50)
 您好，很高兴收到您的回复。我主要聚焦于使用pykoopman包里的NNDMD模块，我在使用的过程中有如下问题:第一，原来的代码里面主要使用的是LBFGS优化器进行优化，使用ADAM优化器得到的效果较差。第二,我把NNDMD模型用于其他的非线性动力学系统的koopman算子的学习，例如duffing振荡子系统，von der pol振荡子系统，所得的结果不能准确的计算其koopman算子，不管是使用LBFGS优化器还是ADAM优化器。我想请问您在使用NNDMD应用到其他的非线性动力学系统上有什么经验，如果可行的话，能不能借鉴您使用NNDMD时应用的示例，供我进一步学习理解。很感谢您的回复，谢谢！ <br&gt; <br&gt; <br&gt; ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------ <br&gt; 发件人:                                                                                                                        &amp;quot;dynamicslab/pykoopman&amp;quot;                                                                                    ***@***.***&amp;amp;gt;; <br&gt; 发送时间:&amp;amp;nbsp;2025年5月11日(星期天) 下午4:23 <br&gt; ***@***.***&amp;amp;gt;; <br&gt; ***@***.******@***.***&amp;amp;gt;; <br&gt; 主题:&amp;amp;nbsp;Re: [dynamicslab/pykoopman] The predicted derivative. (Issue #50) <br&gt; <br&gt; <br&gt; <br&gt;  Dionysus7777777 left a comment (dynamicslab/pykoopman#50) <br&gt;  你好，欢迎交流，鉴于我感觉你也是中国人，所以我直接用中文回复你了，你遇到了什么困难吗？欢迎可以把问题发到这个邮箱，如果我有相关经验我会解答的。 &amp;lt;br&amp;amp;gt; &amp;lt;br&amp;amp;gt; &amp;lt;br&amp;amp;gt; &amp;lt;br&amp;amp;gt; 发自我的iPhone &amp;lt;br&amp;amp;gt; &amp;lt;br&amp;amp;gt; &amp;lt;br&amp;amp;gt; ------------------ Original ------------------ &amp;lt;br&amp;amp;gt; From: goya-ddddd ***@***.***&amp;amp;amp;amp;gt; &amp;lt;br&amp;amp;gt; Date: Sun,May 11,2025 1:13 AM &amp;lt;br&amp;amp;gt; To: dynamicslab/pykoopman ***@***.***&amp;amp;amp;amp;gt; &amp;lt;br&amp;amp;gt; Cc: Dionysus7777777 ***@***.***&amp;amp;amp;amp;gt;, State change ***@***.***&amp;amp;amp;amp;gt; &amp;lt;br&amp;amp;gt; Subject: Re: [dynamicslab/pykoopman] The predicted derivative. (Issue #50) &amp;lt;br&amp;amp;gt; &amp;lt;br&amp;amp;gt; &amp;lt;br&amp;amp;gt; &amp;lt;br&amp;amp;gt;  fdu-goya left a comment (dynamicslab/pykoopman#50) &amp;lt;br&amp;amp;gt;   &amp;lt;br&amp;amp;gt; Hello, I noticed that you have conducted in-depth research using pykoopman. I have also recently been studying the application of pyKoopman to different nonlinear dynamical systems. Could we exchange insights on its usage? I would be very happy to get in touch with you. Thank you. &amp;lt;br&amp;amp;gt;   &amp;lt;br&amp;amp;gt; — &amp;lt;br&amp;amp;gt; Reply to this email directly, view it on GitHub, or unsubscribe. &amp;lt;br&amp;amp;gt; You are receiving this because you modified the open/close state.Message ID: ***@***.***&amp;amp;amp;amp;gt;  <br&gt; — <br&gt; Reply to this email directly, view it on GitHub, or unsubscribe. <br&gt; You are receiving this because you commented.Message ID: ***@***.***&amp;amp;gt;

**Comment by fdu-goya** [comment]
好的，谢谢您！我注意到了您其他的issue对话，这是我的QQ邮箱：1737885592@qq.com，希望下周能和您讨论一下。

**Comment by fdu-goya** [comment]
您好，我想和您进一步交流pykoopman的学习，您目前有使用pykoopman运行较好的示例吗，供我参考学习使用，您主要是用于什么系统的koopman算子学习呢
